# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Multi-stage Dockerfile for SSH MCP Server

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and source code first
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and TypeScript compiler
RUN npm install

# Build the project
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies without running scripts
COPY package.json package-lock.json ./
RUN npm install --omit=dev --ignore-scripts

# Copy compiled code
COPY --from=builder /app/build ./build

# Default command to run the MCP server
CMD ["node", "build/index.js"]