# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Install build dependencies
env npm_config_loglevel=warn
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install && \
    npm run build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app
# Copy built files and runtime dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts --omit=dev && \
    mkdir build
COPY --from=builder /app/build ./build

ENTRYPOINT ["node", "build/index.js"]
