# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Multi-stage Dockerfile for SSH MCP Server

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and TypeScript compiler
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

# Copy source and compile
COPY src ./src
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy compiled code
COPY --from=builder /app/build ./build

# Default command to run the MCP server
CMD ["node", "build/index.js"]